import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import Welcome from '@/components/content/Welcome'

import dynamic from 'next/dynamic';
import { useState } from 'react';

const WelcomeComponenLoading = dynamic(() => import("/components/content/WelcomeComponenLoading"),{
  loading : () => <h5>Please waiting for loading data</h5>
});
const WelcomeComponenSsr = dynamic(() => import("/components/content/WelcomeComponenSsr"),{
  ssr:true
});
const WelcomeComponenNoSsr = dynamic(() => import("/components/content/WelcomeComponenNoSsr"),{
  ssr:true
});


export default function Home() {
  const [tampil,setTampil] = useState(false);

  const showDynamic = () => {
    setTampil(!tampil);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className='text-center'>Welcome To My Website</h3>
        <div className='row'>
          <div className='col-md-4'>
            <h6>Component Langsung tampil</h6>
            <Welcome />
          </div>
          <div className='col-md-4'>
            <h6>Component Dynamic ssr</h6>
            <WelcomeComponenSsr />
          </div>
          <div className='col-md-4'>
            <h6>Component Dynamic ssr false</h6>
            <WelcomeComponenNoSsr />
          </div>
          <div className='col-md-4'>
            <h6>Component Dynamic Loading</h6>
            {
              tampil && (
                <WelcomeComponenLoading />
              )
            }
            
            <button className='btn' onClick={showDynamic}>show Image</button>
          </div>
        </div>
      
        
        

        
      </main>
    </div>
  )
}
